name: Scala/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  small-designs:
    runs-on: ubuntu-latest

    steps:
      - uses: olafurpg/setup-scala@v14
      - name: checkout essent & firrtl-sig
        uses: actions/checkout@v4
        with:
            submodules: true

      - name: build stuff
        run: sbt compile

      - name: run small designs
        run: sbt 'run all'
